# Data Configuration
data:
  symbols: ['AAPL', 'MSFT', 'GOOGL', 'AMZN', 'META']  # Initial test with major tech stocks
  start_date: '2018-01-01'
  end_date: '2024-01-01'
  sequence_length: 60  # 60 days of historical data
  prediction_horizon: 5  # Predict 5 days ahead
  train_test_split: 0.8
  validation_split: 0.1

# Model Configuration
model:
  d_feat: 110  # Number of input features
  d_model: 256  # Model dimension
  n_heads: 4
  use_patches: false  # Set to true only if needed for computational efficiency
  patch_size: 10  # Only used if use_patches is true
  dropout: 0.1
  n_layers: 3

# Training Configuration
training:
  batch_size: 64
  learning_rate: 0.001
  epochs: 100
  early_stopping_patience: 10
  optimizer: 'adam'
  loss_function: 'mse'
  scheduler_step_size: 30
  scheduler_gamma: 0.1

# Paths
paths:
  data_dir: 'data/raw'
  processed_dir: 'data/processed'
  model_dir: 'models/saved'
  results_dir: 'results'
